# Generated by Django 6.0 on 2026-01-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('food_img', models.ImageField(blank=True, null=True, upload_to='foodimg/')),
            ],
        ),
    ]
