# Generated by Django 6.0 on 2026-01-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_fooditems_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='Category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGERS', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'BREVERAGES')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
