# Generated by Django 6.0 on 2026-01-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_fooditems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='Category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGERS', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'BREVERAGES'), ('MAIN_COURSE', 'Main_Course'), ('ROOLS', 'ROOLS')], max_length=100),
        ),
    ]
