# Generated by Django 6.0 on 2026-01-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_fooditems_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
