# Generated by Django 6.0 on 2026-01-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_basetype_sauces_sizechart_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetype',
            name='base_image',
            field=models.ImageField(upload_to='media/customizeimg/baseimg/'),
        ),
        migrations.AlterField(
            model_name='sauces',
            name='sauce_image',
            field=models.ImageField(upload_to='media/customizeimg/saucesimg/'),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='topping_image',
            field=models.ImageField(upload_to='media/customizeimg/toppingsimg/'),
        ),
        migrations.CreateModel(
            name='Customized_Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGERS', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'BREVERAGES'), ('MAIN_COURSE', 'Main_Course'), ('ROOLS AND SANDWICH', 'Rools and SandWich')], max_length=100)),
                ('Base_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizecharts', to='foods.sizechart')),
                ('size_charts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saucess', to='foods.sauces')),
                ('toppings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppingss', to='foods.toppings')),
            ],
        ),
    ]
