# Generated by Django 6.0 on 2026-01-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_alter_basetype_base_image_alter_sauces_sauce_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customized_options',
            old_name='size_charts',
            new_name='sauces',
        ),
        migrations.AddField(
            model_name='customized_options',
            name='Sizechart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizecharts', to='foods.sizechart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customized_options',
            name='Base_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basetypes', to='foods.basetype'),
        ),
    ]
