# Generated by Django 6.0 on 2026-01-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_rename_size_charts_customized_options_sauces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetype',
            name='base_image',
            field=models.ImageField(upload_to='customizeimg/baseimg/'),
        ),
        migrations.AlterField(
            model_name='sauces',
            name='sauce_image',
            field=models.ImageField(upload_to='customizeimg/saucesimg/'),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='topping_image',
            field=models.ImageField(upload_to='customizeimg/toppingsimg/'),
        ),
    ]
