# Generated by Django 6.0 on 2026-03-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='Category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='food_img',
            field=models.ImageField(default=1, upload_to='foods/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='rating',
            field=models.FloatField(),
        ),
    ]
