# Generated by Django 6.0 on 2026-03-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_alter_fooditems_category_alter_fooditems_food_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customized_options',
            name='Base_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.basetype'),
        ),
        migrations.AlterField(
            model_name='customized_options',
            name='Sizechart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.sizechart'),
        ),
        migrations.AlterField(
            model_name='customized_options',
            name='food_name',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGERS', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Beverages'), ('MAIN_COURSE', 'Main Course'), ('ROOLS AND SANDWICH', 'Rools and Sandwich')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customized_options',
            name='sauces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.sauces'),
        ),
        migrations.AlterField(
            model_name='customized_options',
            name='toppings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.toppings'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='Category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGERS', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Beverages'), ('MAIN_COURSE', 'Main Course'), ('ROOLS AND SANDWICH', 'Rools and Sandwich')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='food_img',
            field=models.ImageField(blank=True, null=True, upload_to='foodimg/'),
        ),
    ]
