# Generated by Django 6.0 on 2026-03-14 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_remove_order_name_remove_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food_img',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rating',
        ),
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems'),
            preserve_default=False,
        ),
    ]
