# Generated by Django 6.0 on 2026-03-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0018_remove_cart_food_img_remove_cart_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.AddField(
            model_name='cart',
            name='food_img',
            field=models.ImageField(blank=True, null=True, upload_to='cartimg/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
