# Generated by Django 6.0 on 2026-03-15 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0019_remove_cart_food_cart_food_img_cart_name_cart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foods.fooditems'),
            preserve_default=False,
        ),
    ]
