# Generated by Django 6.0 on 2026-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0002_userdetails_address_userdetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('USER', 'User')], default='User', max_length=100),
        ),
    ]
