# Generated by Django 6.0 on 2026-01-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0003_userdetails_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('USER', 'User')], default='USER', max_length=100),
        ),
    ]
